controller:
  tag: "alpine"
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  imagePullPolicy: "Always"
  serviceType: ClusterIP
  installPlugins:
  - durable-task:latest
  - workflow-durable-task-step:latest
  - blueocean:latest
  - configuration-as-code:latest
  - credentials:latest
  - ec2:latest
  - git:latest
  - git-client:latest
  - github:latest
  - kubernetes:latest
  - pipeline-utility-steps:latest
  - pipeline-model-definition:latest
  - slack:latest
  - thinBackup:latest
  - workflow-aggregator:latest
  - ssh-slaves:latest
  - ssh-agent:latest
  - jdk-tool:latest
  - command-launcher:latest
  - github-oauth:latest
  - google-compute-engine:latest
  ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: jenkins
          port:
            number: 8080
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: 192.168.64.167.nip.io
rbac:
  create: true
